version: "3.9"

services:
  freqtrade-pairlist:
    image: freqtradeorg/freqtrade:stable
    container_name: freqtrade_pairlist
    restart: "no"
    volumes:
      - "/zfspool/Appdata/freqtradeio/user_data:/freqtrade/user_data"
    entrypoint: >
      /bin/bash -c "freqtrade list-pairs --config /freqtrade/user_data/extase_bot_1_momentum_l2.json --quote USDC --print-json > /freqtrade/user_data/data/hyperliquid/pairlist.json"
