name: Test Freqtrade in Docker

on:
  workflow_dispatch:

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Pull Freqtrade Docker image
      run: |
        docker pull freqtradeorg/freqtrade:stable

    - name: Run Freqtrade container
      run: |
        # Créer un répertoire temporaire pour les données
        mkdir -p ./user_data/data/hyperliquid
        
        # Lancer le conteneur avec une commande shell pour générer le fichier JSON
        docker run --rm \
          -v "${{ github.workspace }}/user_data:/freqtrade/user_data" \
          freqtradeorg/freqtrade:stable \
          /bin/bash -c "mkdir -p /freqtrade/user_data/data/hyperliquid && freqtrade list-pairs --config /freqtrade/user_data/hyperliquid_futures_volume.json --quote USDC --print-json > /freqtrade/user_data/data/hyperliquid/pairlist.json"

    - name: Check if JSON was generated
      run: |
        if [ ! -f ./user_data/data/hyperliquid/pairlist.json ]; then
          echo "File pairlist.json was not generated!"
          exit 1
        else
          echo "File pairlist.json was successfully generated!"
        fi

    - name: Display JSON output
      run: |
        cat ./user_data/data/hyperliquid/pairlist.json

